### ISSUE TITLE
Email template changes are not saved correctly (Admin Console)

### ISSUE THREAD

**Issue by ammannm** [p2-inc/keycloak-theme-template#5]
Dear Phase Two Team

### Settings

- Docker-Image: _quay.io/phasetwo/phasetwo-keycloak:26.3.2.1753977298_

```
--spi-email-template-provider=„freemarker-plus-mustache“
--spi-email-template-freemarker-plus-mustache-enabled=„true“
--spi-theme-cache-themes=„false“
```

### Plan
I want to change the existing templates in the admin view. In “Realm settings” -> ‘Themes’ -> “Email theme,” I have the following value: “attributs.”

### Problem
Under “Styles” -> “Emails,” I can select the themes, add text, and supposedly save them. The message indicating that the update was successful also appears in the UI.
Unfortunately, all changes disappear after reloading the page, and even after resetting the password, the changes are not visible in the email. 

### Log

```
2025-08-15T12:24:49.553174864Z 2025-08-15 12:24:49,553 DEBUG [io.phasetwo.keycloak.themes.resource.BaseRealmResourceProvider] (executor-thread-490) request method PUT
2025-08-15T12:24:49.554461910Z 2025-08-15 12:24:49,554 DEBUG [io.phasetwo.keycloak.themes.resource.EmailsResource] (executor-thread-490) setting realm attribute _providerConfig.theme.email.templates.html/email-verification.mustache to <html>
2025-08-15T12:24:49.554500141Z <body>
2025-08-15T12:24:49.554513627Z     <p>Someone has created a {{realmName}} account with this email address. If this was you, click the link below to verify your email address</p><p><a href="{{link}}">Link to e-mail address verification</a></p><p>This link will expire within {{#linkExpirationFormatter}}{{linkExpiration}}{{/linkExpirationFormatter}}.</p><p>If you didn''t create this account, just ignore this message.</p>
2025-08-15T12:24:49.554522102Z 
2025-08-15T12:24:49.554529456Z >>>>>>> HERE MY CHANGES!
2025-08-15T12:24:49.554536058Z 
2025-08-15T12:24:49.554543152Z </body>
2025-08-15T12:24:49.554549764Z </html>
2025-08-15T12:24:49.585139017Z 2025-08-15 12:24:49,585 DEBUG [io.phasetwo.keycloak.themes.resource.BaseRealmResourceProvider] (executor-thread-491) request method PUT
2025-08-15T12:24:49.586493011Z 2025-08-15 12:24:49,586 DEBUG [io.phasetwo.keycloak.themes.resource.EmailsResource] (executor-thread-491) setting realm attribute _providerConfig.theme.email.templates.text/email-verification.mustache to Someone has created a {{realmName}} account with this email address. If this was you, click the link below to verify your email address.
2025-08-15T12:24:49.586524559Z 
2025-08-15T12:24:49.586533286Z {{link}}
2025-08-15T12:24:49.586540039Z 
2025-08-15T12:24:49.586573711Z This link will expire within {{#linkExpirationFormatter}}{{linkExpiration}}{{/linkExpirationFormatter}}.
2025-08-15T12:24:49.586581606Z 
2025-08-15T12:24:49.586589230Z If you didn't create this account, just ignore this message.
2025-08-15T12:24:49.586595743Z 
```

Am I doing something wrong?
Are the settings incorrect?
What information is missing so that someone can help me?

Thank you very much for your help!
Michael

PS: If anyone else can tell me whether {{ user.locale }} works, I would be grateful, as I need to have the template in four languages :-)

**Comment by xgp** [comment]
@pnzrr this might be that the UI has the old realm representation and it is overwriting the stored attributes. Can you check?

**Comment by pnzrr** [comment]
Fixed UI, needed to refresh the context. Thanks for the report @ammannm!

https://github.com/p2-inc/phasetwo-containers/pull/86

**Comment by Lonzak** [comment]
Into which version did the fix go?

**Comment by Lonzak** [comment]
We are running keycloak:26.6.2 and it still doesn't work. Any changes won't be saved. (But we are not running the p2 docker image though)
